# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='intent.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0cintent.proto\"\xa8\x02\n\x07Request\x12\x1f\n\x06method\x18\x08 \x01(\x0e\x32\x0f.Request.Method\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x11\n\tclassName\x18\x02 \x01(\t\x12\x13\n\x0bpackageName\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x12\n\ncategories\x18\x05 \x03(\t\x12\x0b\n\x03uri\x18\x06 \x01(\t\x12$\n\x06\x65xtras\x18\x07 \x03(\x0b\x32\x14.Request.ExtrasEntry\x1a-\n\x0b\x45xtrasEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"@\n\x06Method\x12\x11\n\rstartActivity\x10\x00\x12\x10\n\x0cstartService\x10\x01\x12\x11\n\rsendBroadcast\x10\x02\x42\x34\n\'com.github.hsingpeng.extendbinder.protoB\tIntentMsgb\x06proto3')
)



_REQUEST_METHOD = _descriptor.EnumDescriptor(
  name='Method',
  full_name='Request.Method',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='startActivity', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='startService', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sendBroadcast', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=249,
  serialized_end=313,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_METHOD)


_REQUEST_EXTRASENTRY = _descriptor.Descriptor(
  name='ExtrasEntry',
  full_name='Request.ExtrasEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Request.ExtrasEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Request.ExtrasEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=247,
)

_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='Request.method', index=0,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='Request.action', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='className', full_name='Request.className', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packageName', full_name='Request.packageName', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='Request.type', index=4,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='categories', full_name='Request.categories', index=5,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uri', full_name='Request.uri', index=6,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extras', full_name='Request.extras', index=7,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_EXTRASENTRY, ],
  enum_types=[
    _REQUEST_METHOD,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=313,
)

_REQUEST_EXTRASENTRY.containing_type = _REQUEST
_REQUEST.fields_by_name['method'].enum_type = _REQUEST_METHOD
_REQUEST.fields_by_name['extras'].message_type = _REQUEST_EXTRASENTRY
_REQUEST_METHOD.containing_type = _REQUEST
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(

  ExtrasEntry = _reflection.GeneratedProtocolMessageType('ExtrasEntry', (_message.Message,), dict(
    DESCRIPTOR = _REQUEST_EXTRASENTRY,
    __module__ = 'intent_pb2'
    # @@protoc_insertion_point(class_scope:Request.ExtrasEntry)
    ))
  ,
  DESCRIPTOR = _REQUEST,
  __module__ = 'intent_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  ))
_sym_db.RegisterMessage(Request)
_sym_db.RegisterMessage(Request.ExtrasEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\'com.github.hsingpeng.extendbinder.protoB\tIntentMsg'))
_REQUEST_EXTRASENTRY.has_options = True
_REQUEST_EXTRASENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
