// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_info.proto

package com.github.hsingpeng.extendbinder.proto;

public final class AppInfoMsg {
  private AppInfoMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Info)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string activityList = 1;</code>
     */
    java.util.List<java.lang.String>
        getActivityListList();
    /**
     * <code>repeated string activityList = 1;</code>
     */
    int getActivityListCount();
    /**
     * <code>repeated string activityList = 1;</code>
     */
    java.lang.String getActivityList(int index);
    /**
     * <code>repeated string activityList = 1;</code>
     */
    com.google.protobuf.ByteString
        getActivityListBytes(int index);

    /**
     * <code>repeated string serviceList = 2;</code>
     */
    java.util.List<java.lang.String>
        getServiceListList();
    /**
     * <code>repeated string serviceList = 2;</code>
     */
    int getServiceListCount();
    /**
     * <code>repeated string serviceList = 2;</code>
     */
    java.lang.String getServiceList(int index);
    /**
     * <code>repeated string serviceList = 2;</code>
     */
    com.google.protobuf.ByteString
        getServiceListBytes(int index);

    /**
     * <code>repeated string broadcastList = 3;</code>
     */
    java.util.List<java.lang.String>
        getBroadcastListList();
    /**
     * <code>repeated string broadcastList = 3;</code>
     */
    int getBroadcastListCount();
    /**
     * <code>repeated string broadcastList = 3;</code>
     */
    java.lang.String getBroadcastList(int index);
    /**
     * <code>repeated string broadcastList = 3;</code>
     */
    com.google.protobuf.ByteString
        getBroadcastListBytes(int index);

    /**
     * <code>repeated string contentProviderList = 4;</code>
     */
    java.util.List<java.lang.String>
        getContentProviderListList();
    /**
     * <code>repeated string contentProviderList = 4;</code>
     */
    int getContentProviderListCount();
    /**
     * <code>repeated string contentProviderList = 4;</code>
     */
    java.lang.String getContentProviderList(int index);
    /**
     * <code>repeated string contentProviderList = 4;</code>
     */
    com.google.protobuf.ByteString
        getContentProviderListBytes(int index);
  }
  /**
   * Protobuf type {@code Info}
   */
  public  static final class Info extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Info)
      InfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Info.newBuilder() to construct.
    private Info(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Info() {
      activityList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      serviceList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      broadcastList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      contentProviderList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Info(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                activityList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              activityList_.add(s);
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                serviceList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              serviceList_.add(s);
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                broadcastList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              broadcastList_.add(s);
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                contentProviderList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              contentProviderList_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          activityList_ = activityList_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          serviceList_ = serviceList_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          broadcastList_ = broadcastList_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          contentProviderList_ = contentProviderList_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.hsingpeng.extendbinder.proto.AppInfoMsg.internal_static_Info_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.hsingpeng.extendbinder.proto.AppInfoMsg.internal_static_Info_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info.class, com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info.Builder.class);
    }

    public static final int ACTIVITYLIST_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList activityList_;
    /**
     * <code>repeated string activityList = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getActivityListList() {
      return activityList_;
    }
    /**
     * <code>repeated string activityList = 1;</code>
     */
    public int getActivityListCount() {
      return activityList_.size();
    }
    /**
     * <code>repeated string activityList = 1;</code>
     */
    public java.lang.String getActivityList(int index) {
      return activityList_.get(index);
    }
    /**
     * <code>repeated string activityList = 1;</code>
     */
    public com.google.protobuf.ByteString
        getActivityListBytes(int index) {
      return activityList_.getByteString(index);
    }

    public static final int SERVICELIST_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList serviceList_;
    /**
     * <code>repeated string serviceList = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getServiceListList() {
      return serviceList_;
    }
    /**
     * <code>repeated string serviceList = 2;</code>
     */
    public int getServiceListCount() {
      return serviceList_.size();
    }
    /**
     * <code>repeated string serviceList = 2;</code>
     */
    public java.lang.String getServiceList(int index) {
      return serviceList_.get(index);
    }
    /**
     * <code>repeated string serviceList = 2;</code>
     */
    public com.google.protobuf.ByteString
        getServiceListBytes(int index) {
      return serviceList_.getByteString(index);
    }

    public static final int BROADCASTLIST_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList broadcastList_;
    /**
     * <code>repeated string broadcastList = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getBroadcastListList() {
      return broadcastList_;
    }
    /**
     * <code>repeated string broadcastList = 3;</code>
     */
    public int getBroadcastListCount() {
      return broadcastList_.size();
    }
    /**
     * <code>repeated string broadcastList = 3;</code>
     */
    public java.lang.String getBroadcastList(int index) {
      return broadcastList_.get(index);
    }
    /**
     * <code>repeated string broadcastList = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBroadcastListBytes(int index) {
      return broadcastList_.getByteString(index);
    }

    public static final int CONTENTPROVIDERLIST_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList contentProviderList_;
    /**
     * <code>repeated string contentProviderList = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getContentProviderListList() {
      return contentProviderList_;
    }
    /**
     * <code>repeated string contentProviderList = 4;</code>
     */
    public int getContentProviderListCount() {
      return contentProviderList_.size();
    }
    /**
     * <code>repeated string contentProviderList = 4;</code>
     */
    public java.lang.String getContentProviderList(int index) {
      return contentProviderList_.get(index);
    }
    /**
     * <code>repeated string contentProviderList = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContentProviderListBytes(int index) {
      return contentProviderList_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < activityList_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, activityList_.getRaw(i));
      }
      for (int i = 0; i < serviceList_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serviceList_.getRaw(i));
      }
      for (int i = 0; i < broadcastList_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, broadcastList_.getRaw(i));
      }
      for (int i = 0; i < contentProviderList_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, contentProviderList_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < activityList_.size(); i++) {
          dataSize += computeStringSizeNoTag(activityList_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getActivityListList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < serviceList_.size(); i++) {
          dataSize += computeStringSizeNoTag(serviceList_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getServiceListList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < broadcastList_.size(); i++) {
          dataSize += computeStringSizeNoTag(broadcastList_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getBroadcastListList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < contentProviderList_.size(); i++) {
          dataSize += computeStringSizeNoTag(contentProviderList_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getContentProviderListList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info)) {
        return super.equals(obj);
      }
      com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info other = (com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info) obj;

      boolean result = true;
      result = result && getActivityListList()
          .equals(other.getActivityListList());
      result = result && getServiceListList()
          .equals(other.getServiceListList());
      result = result && getBroadcastListList()
          .equals(other.getBroadcastListList());
      result = result && getContentProviderListList()
          .equals(other.getContentProviderListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getActivityListCount() > 0) {
        hash = (37 * hash) + ACTIVITYLIST_FIELD_NUMBER;
        hash = (53 * hash) + getActivityListList().hashCode();
      }
      if (getServiceListCount() > 0) {
        hash = (37 * hash) + SERVICELIST_FIELD_NUMBER;
        hash = (53 * hash) + getServiceListList().hashCode();
      }
      if (getBroadcastListCount() > 0) {
        hash = (37 * hash) + BROADCASTLIST_FIELD_NUMBER;
        hash = (53 * hash) + getBroadcastListList().hashCode();
      }
      if (getContentProviderListCount() > 0) {
        hash = (37 * hash) + CONTENTPROVIDERLIST_FIELD_NUMBER;
        hash = (53 * hash) + getContentProviderListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Info}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Info)
        com.github.hsingpeng.extendbinder.proto.AppInfoMsg.InfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.hsingpeng.extendbinder.proto.AppInfoMsg.internal_static_Info_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.hsingpeng.extendbinder.proto.AppInfoMsg.internal_static_Info_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info.class, com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info.Builder.class);
      }

      // Construct using com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        activityList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        broadcastList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        contentProviderList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.hsingpeng.extendbinder.proto.AppInfoMsg.internal_static_Info_descriptor;
      }

      public com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info getDefaultInstanceForType() {
        return com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info.getDefaultInstance();
      }

      public com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info build() {
        com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info buildPartial() {
        com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info result = new com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          activityList_ = activityList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.activityList_ = activityList_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          serviceList_ = serviceList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.serviceList_ = serviceList_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          broadcastList_ = broadcastList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.broadcastList_ = broadcastList_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          contentProviderList_ = contentProviderList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.contentProviderList_ = contentProviderList_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info) {
          return mergeFrom((com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info other) {
        if (other == com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info.getDefaultInstance()) return this;
        if (!other.activityList_.isEmpty()) {
          if (activityList_.isEmpty()) {
            activityList_ = other.activityList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureActivityListIsMutable();
            activityList_.addAll(other.activityList_);
          }
          onChanged();
        }
        if (!other.serviceList_.isEmpty()) {
          if (serviceList_.isEmpty()) {
            serviceList_ = other.serviceList_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureServiceListIsMutable();
            serviceList_.addAll(other.serviceList_);
          }
          onChanged();
        }
        if (!other.broadcastList_.isEmpty()) {
          if (broadcastList_.isEmpty()) {
            broadcastList_ = other.broadcastList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureBroadcastListIsMutable();
            broadcastList_.addAll(other.broadcastList_);
          }
          onChanged();
        }
        if (!other.contentProviderList_.isEmpty()) {
          if (contentProviderList_.isEmpty()) {
            contentProviderList_ = other.contentProviderList_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureContentProviderListIsMutable();
            contentProviderList_.addAll(other.contentProviderList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList activityList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureActivityListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          activityList_ = new com.google.protobuf.LazyStringArrayList(activityList_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string activityList = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getActivityListList() {
        return activityList_.getUnmodifiableView();
      }
      /**
       * <code>repeated string activityList = 1;</code>
       */
      public int getActivityListCount() {
        return activityList_.size();
      }
      /**
       * <code>repeated string activityList = 1;</code>
       */
      public java.lang.String getActivityList(int index) {
        return activityList_.get(index);
      }
      /**
       * <code>repeated string activityList = 1;</code>
       */
      public com.google.protobuf.ByteString
          getActivityListBytes(int index) {
        return activityList_.getByteString(index);
      }
      /**
       * <code>repeated string activityList = 1;</code>
       */
      public Builder setActivityList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureActivityListIsMutable();
        activityList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string activityList = 1;</code>
       */
      public Builder addActivityList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureActivityListIsMutable();
        activityList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string activityList = 1;</code>
       */
      public Builder addAllActivityList(
          java.lang.Iterable<java.lang.String> values) {
        ensureActivityListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, activityList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string activityList = 1;</code>
       */
      public Builder clearActivityList() {
        activityList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string activityList = 1;</code>
       */
      public Builder addActivityListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureActivityListIsMutable();
        activityList_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList serviceList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureServiceListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          serviceList_ = new com.google.protobuf.LazyStringArrayList(serviceList_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string serviceList = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getServiceListList() {
        return serviceList_.getUnmodifiableView();
      }
      /**
       * <code>repeated string serviceList = 2;</code>
       */
      public int getServiceListCount() {
        return serviceList_.size();
      }
      /**
       * <code>repeated string serviceList = 2;</code>
       */
      public java.lang.String getServiceList(int index) {
        return serviceList_.get(index);
      }
      /**
       * <code>repeated string serviceList = 2;</code>
       */
      public com.google.protobuf.ByteString
          getServiceListBytes(int index) {
        return serviceList_.getByteString(index);
      }
      /**
       * <code>repeated string serviceList = 2;</code>
       */
      public Builder setServiceList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureServiceListIsMutable();
        serviceList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string serviceList = 2;</code>
       */
      public Builder addServiceList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureServiceListIsMutable();
        serviceList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string serviceList = 2;</code>
       */
      public Builder addAllServiceList(
          java.lang.Iterable<java.lang.String> values) {
        ensureServiceListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, serviceList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string serviceList = 2;</code>
       */
      public Builder clearServiceList() {
        serviceList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string serviceList = 2;</code>
       */
      public Builder addServiceListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureServiceListIsMutable();
        serviceList_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList broadcastList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureBroadcastListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          broadcastList_ = new com.google.protobuf.LazyStringArrayList(broadcastList_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string broadcastList = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getBroadcastListList() {
        return broadcastList_.getUnmodifiableView();
      }
      /**
       * <code>repeated string broadcastList = 3;</code>
       */
      public int getBroadcastListCount() {
        return broadcastList_.size();
      }
      /**
       * <code>repeated string broadcastList = 3;</code>
       */
      public java.lang.String getBroadcastList(int index) {
        return broadcastList_.get(index);
      }
      /**
       * <code>repeated string broadcastList = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBroadcastListBytes(int index) {
        return broadcastList_.getByteString(index);
      }
      /**
       * <code>repeated string broadcastList = 3;</code>
       */
      public Builder setBroadcastList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBroadcastListIsMutable();
        broadcastList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string broadcastList = 3;</code>
       */
      public Builder addBroadcastList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBroadcastListIsMutable();
        broadcastList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string broadcastList = 3;</code>
       */
      public Builder addAllBroadcastList(
          java.lang.Iterable<java.lang.String> values) {
        ensureBroadcastListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, broadcastList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string broadcastList = 3;</code>
       */
      public Builder clearBroadcastList() {
        broadcastList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string broadcastList = 3;</code>
       */
      public Builder addBroadcastListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureBroadcastListIsMutable();
        broadcastList_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList contentProviderList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureContentProviderListIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          contentProviderList_ = new com.google.protobuf.LazyStringArrayList(contentProviderList_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string contentProviderList = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getContentProviderListList() {
        return contentProviderList_.getUnmodifiableView();
      }
      /**
       * <code>repeated string contentProviderList = 4;</code>
       */
      public int getContentProviderListCount() {
        return contentProviderList_.size();
      }
      /**
       * <code>repeated string contentProviderList = 4;</code>
       */
      public java.lang.String getContentProviderList(int index) {
        return contentProviderList_.get(index);
      }
      /**
       * <code>repeated string contentProviderList = 4;</code>
       */
      public com.google.protobuf.ByteString
          getContentProviderListBytes(int index) {
        return contentProviderList_.getByteString(index);
      }
      /**
       * <code>repeated string contentProviderList = 4;</code>
       */
      public Builder setContentProviderList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureContentProviderListIsMutable();
        contentProviderList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string contentProviderList = 4;</code>
       */
      public Builder addContentProviderList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureContentProviderListIsMutable();
        contentProviderList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string contentProviderList = 4;</code>
       */
      public Builder addAllContentProviderList(
          java.lang.Iterable<java.lang.String> values) {
        ensureContentProviderListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, contentProviderList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string contentProviderList = 4;</code>
       */
      public Builder clearContentProviderList() {
        contentProviderList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string contentProviderList = 4;</code>
       */
      public Builder addContentProviderListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureContentProviderListIsMutable();
        contentProviderList_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Info)
    }

    // @@protoc_insertion_point(class_scope:Info)
    private static final com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info();
    }

    public static com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Info>
        PARSER = new com.google.protobuf.AbstractParser<Info>() {
      public Info parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Info(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Info> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Info> getParserForType() {
      return PARSER;
    }

    public com.github.hsingpeng.extendbinder.proto.AppInfoMsg.Info getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Info_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Info_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016app_info.proto\"e\n\004Info\022\024\n\014activityList" +
      "\030\001 \003(\t\022\023\n\013serviceList\030\002 \003(\t\022\025\n\rbroadcast" +
      "List\030\003 \003(\t\022\033\n\023contentProviderList\030\004 \003(\tB" +
      "5\n\'com.github.hsingpeng.extendbinder.pro" +
      "toB\nAppInfoMsgb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Info_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Info_descriptor,
        new java.lang.String[] { "ActivityList", "ServiceList", "BroadcastList", "ContentProviderList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
