// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: content_provider.proto

package com.github.hsingpeng.extendbinder.proto;

public final class ContentProviderMsg {
  private ContentProviderMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uuid = 1;</code>
     */
    java.lang.String getUuid();
    /**
     * <code>string uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>.Request.Method method = 2;</code>
     */
    int getMethodValue();
    /**
     * <code>.Request.Method method = 2;</code>
     */
    com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.Method getMethod();

    /**
     * <pre>
     *method params
     * </pre>
     *
     * <code>string uri = 3;</code>
     */
    java.lang.String getUri();
    /**
     * <pre>
     *method params
     * </pre>
     *
     * <code>string uri = 3;</code>
     */
    com.google.protobuf.ByteString
        getUriBytes();

    /**
     * <code>string selection = 4;</code>
     */
    java.lang.String getSelection();
    /**
     * <code>string selection = 4;</code>
     */
    com.google.protobuf.ByteString
        getSelectionBytes();

    /**
     * <code>repeated string selectionArgs = 5;</code>
     */
    java.util.List<java.lang.String>
        getSelectionArgsList();
    /**
     * <code>repeated string selectionArgs = 5;</code>
     */
    int getSelectionArgsCount();
    /**
     * <code>repeated string selectionArgs = 5;</code>
     */
    java.lang.String getSelectionArgs(int index);
    /**
     * <code>repeated string selectionArgs = 5;</code>
     */
    com.google.protobuf.ByteString
        getSelectionArgsBytes(int index);

    /**
     * <code>map&lt;string, string&gt; values = 6;</code>
     */
    int getValuesCount();
    /**
     * <code>map&lt;string, string&gt; values = 6;</code>
     */
    boolean containsValues(
        java.lang.String key);
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getValues();
    /**
     * <code>map&lt;string, string&gt; values = 6;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getValuesMap();
    /**
     * <code>map&lt;string, string&gt; values = 6;</code>
     */

    java.lang.String getValuesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; values = 6;</code>
     */

    java.lang.String getValuesOrThrow(
        java.lang.String key);

    /**
     * <code>repeated string projection = 7;</code>
     */
    java.util.List<java.lang.String>
        getProjectionList();
    /**
     * <code>repeated string projection = 7;</code>
     */
    int getProjectionCount();
    /**
     * <code>repeated string projection = 7;</code>
     */
    java.lang.String getProjection(int index);
    /**
     * <code>repeated string projection = 7;</code>
     */
    com.google.protobuf.ByteString
        getProjectionBytes(int index);

    /**
     * <code>string sortOrder = 8;</code>
     */
    java.lang.String getSortOrder();
    /**
     * <code>string sortOrder = 8;</code>
     */
    com.google.protobuf.ByteString
        getSortOrderBytes();
  }
  /**
   * Protobuf type {@code Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      uuid_ = "";
      method_ = 0;
      uri_ = "";
      selection_ = "";
      selectionArgs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      projection_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      sortOrder_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uuid_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              method_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              uri_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              selection_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                selectionArgs_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              selectionArgs_.add(s);
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                values_ = com.google.protobuf.MapField.newMapField(
                    ValuesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000020;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              values__ = input.readMessage(
                  ValuesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              values_.getMutableMap().put(
                  values__.getKey(), values__.getValue());
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                projection_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000040;
              }
              projection_.add(s);
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              sortOrder_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          selectionArgs_ = selectionArgs_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          projection_ = projection_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.internal_static_Request_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.internal_static_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.class, com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.Builder.class);
    }

    /**
     * Protobuf enum {@code Request.Method}
     */
    public enum Method
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>delete = 0;</code>
       */
      delete(0),
      /**
       * <code>getType = 1;</code>
       */
      getType(1),
      /**
       * <code>insert = 2;</code>
       */
      insert(2),
      /**
       * <code>query = 3;</code>
       */
      query(3),
      /**
       * <code>update = 4;</code>
       */
      update(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>delete = 0;</code>
       */
      public static final int delete_VALUE = 0;
      /**
       * <code>getType = 1;</code>
       */
      public static final int getType_VALUE = 1;
      /**
       * <code>insert = 2;</code>
       */
      public static final int insert_VALUE = 2;
      /**
       * <code>query = 3;</code>
       */
      public static final int query_VALUE = 3;
      /**
       * <code>update = 4;</code>
       */
      public static final int update_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Method valueOf(int value) {
        return forNumber(value);
      }

      public static Method forNumber(int value) {
        switch (value) {
          case 0: return delete;
          case 1: return getType;
          case 2: return insert;
          case 3: return query;
          case 4: return update;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Method>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Method> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Method>() {
              public Method findValueByNumber(int number) {
                return Method.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.getDescriptor().getEnumTypes().get(0);
      }

      private static final Method[] VALUES = values();

      public static Method valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Method(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Request.Method)
    }

    private int bitField0_;
    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uuid_;
    /**
     * <code>string uuid = 1;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <code>string uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_FIELD_NUMBER = 2;
    private int method_;
    /**
     * <code>.Request.Method method = 2;</code>
     */
    public int getMethodValue() {
      return method_;
    }
    /**
     * <code>.Request.Method method = 2;</code>
     */
    public com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.Method getMethod() {
      com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.Method result = com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.Method.valueOf(method_);
      return result == null ? com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.Method.UNRECOGNIZED : result;
    }

    public static final int URI_FIELD_NUMBER = 3;
    private volatile java.lang.Object uri_;
    /**
     * <pre>
     *method params
     * </pre>
     *
     * <code>string uri = 3;</code>
     */
    public java.lang.String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uri_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *method params
     * </pre>
     *
     * <code>string uri = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SELECTION_FIELD_NUMBER = 4;
    private volatile java.lang.Object selection_;
    /**
     * <code>string selection = 4;</code>
     */
    public java.lang.String getSelection() {
      java.lang.Object ref = selection_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        selection_ = s;
        return s;
      }
    }
    /**
     * <code>string selection = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSelectionBytes() {
      java.lang.Object ref = selection_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        selection_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SELECTIONARGS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList selectionArgs_;
    /**
     * <code>repeated string selectionArgs = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSelectionArgsList() {
      return selectionArgs_;
    }
    /**
     * <code>repeated string selectionArgs = 5;</code>
     */
    public int getSelectionArgsCount() {
      return selectionArgs_.size();
    }
    /**
     * <code>repeated string selectionArgs = 5;</code>
     */
    public java.lang.String getSelectionArgs(int index) {
      return selectionArgs_.get(index);
    }
    /**
     * <code>repeated string selectionArgs = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSelectionArgsBytes(int index) {
      return selectionArgs_.getByteString(index);
    }

    public static final int VALUES_FIELD_NUMBER = 6;
    private static final class ValuesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.internal_static_Request_ValuesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> values_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetValues() {
      if (values_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ValuesDefaultEntryHolder.defaultEntry);
      }
      return values_;
    }

    public int getValuesCount() {
      return internalGetValues().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; values = 6;</code>
     */

    public boolean containsValues(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetValues().getMap().containsKey(key);
    }
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getValues() {
      return getValuesMap();
    }
    /**
     * <code>map&lt;string, string&gt; values = 6;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getValuesMap() {
      return internalGetValues().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; values = 6;</code>
     */

    public java.lang.String getValuesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetValues().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; values = 6;</code>
     */

    public java.lang.String getValuesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetValues().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int PROJECTION_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList projection_;
    /**
     * <code>repeated string projection = 7;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getProjectionList() {
      return projection_;
    }
    /**
     * <code>repeated string projection = 7;</code>
     */
    public int getProjectionCount() {
      return projection_.size();
    }
    /**
     * <code>repeated string projection = 7;</code>
     */
    public java.lang.String getProjection(int index) {
      return projection_.get(index);
    }
    /**
     * <code>repeated string projection = 7;</code>
     */
    public com.google.protobuf.ByteString
        getProjectionBytes(int index) {
      return projection_.getByteString(index);
    }

    public static final int SORTORDER_FIELD_NUMBER = 8;
    private volatile java.lang.Object sortOrder_;
    /**
     * <code>string sortOrder = 8;</code>
     */
    public java.lang.String getSortOrder() {
      java.lang.Object ref = sortOrder_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sortOrder_ = s;
        return s;
      }
    }
    /**
     * <code>string sortOrder = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSortOrderBytes() {
      java.lang.Object ref = sortOrder_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sortOrder_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      if (method_ != com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.Method.delete.getNumber()) {
        output.writeEnum(2, method_);
      }
      if (!getUriBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, uri_);
      }
      if (!getSelectionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, selection_);
      }
      for (int i = 0; i < selectionArgs_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, selectionArgs_.getRaw(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetValues(),
          ValuesDefaultEntryHolder.defaultEntry,
          6);
      for (int i = 0; i < projection_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, projection_.getRaw(i));
      }
      if (!getSortOrderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, sortOrder_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      if (method_ != com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.Method.delete.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, method_);
      }
      if (!getUriBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, uri_);
      }
      if (!getSelectionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, selection_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < selectionArgs_.size(); i++) {
          dataSize += computeStringSizeNoTag(selectionArgs_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSelectionArgsList().size();
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetValues().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        values__ = ValuesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, values__);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < projection_.size(); i++) {
          dataSize += computeStringSizeNoTag(projection_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getProjectionList().size();
      }
      if (!getSortOrderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, sortOrder_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request)) {
        return super.equals(obj);
      }
      com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request other = (com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request) obj;

      boolean result = true;
      result = result && getUuid()
          .equals(other.getUuid());
      result = result && method_ == other.method_;
      result = result && getUri()
          .equals(other.getUri());
      result = result && getSelection()
          .equals(other.getSelection());
      result = result && getSelectionArgsList()
          .equals(other.getSelectionArgsList());
      result = result && internalGetValues().equals(
          other.internalGetValues());
      result = result && getProjectionList()
          .equals(other.getProjectionList());
      result = result && getSortOrder()
          .equals(other.getSortOrder());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + method_;
      hash = (37 * hash) + URI_FIELD_NUMBER;
      hash = (53 * hash) + getUri().hashCode();
      hash = (37 * hash) + SELECTION_FIELD_NUMBER;
      hash = (53 * hash) + getSelection().hashCode();
      if (getSelectionArgsCount() > 0) {
        hash = (37 * hash) + SELECTIONARGS_FIELD_NUMBER;
        hash = (53 * hash) + getSelectionArgsList().hashCode();
      }
      if (!internalGetValues().getMap().isEmpty()) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetValues().hashCode();
      }
      if (getProjectionCount() > 0) {
        hash = (37 * hash) + PROJECTION_FIELD_NUMBER;
        hash = (53 * hash) + getProjectionList().hashCode();
      }
      hash = (37 * hash) + SORTORDER_FIELD_NUMBER;
      hash = (53 * hash) + getSortOrder().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Request)
        com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.internal_static_Request_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.internal_static_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.class, com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.Builder.class);
      }

      // Construct using com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uuid_ = "";

        method_ = 0;

        uri_ = "";

        selection_ = "";

        selectionArgs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        internalGetMutableValues().clear();
        projection_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        sortOrder_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.internal_static_Request_descriptor;
      }

      public com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request getDefaultInstanceForType() {
        return com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.getDefaultInstance();
      }

      public com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request build() {
        com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request buildPartial() {
        com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request result = new com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.uuid_ = uuid_;
        result.method_ = method_;
        result.uri_ = uri_;
        result.selection_ = selection_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          selectionArgs_ = selectionArgs_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.selectionArgs_ = selectionArgs_;
        result.values_ = internalGetValues();
        result.values_.makeImmutable();
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          projection_ = projection_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.projection_ = projection_;
        result.sortOrder_ = sortOrder_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request) {
          return mergeFrom((com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request other) {
        if (other == com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.getDefaultInstance()) return this;
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.method_ != 0) {
          setMethodValue(other.getMethodValue());
        }
        if (!other.getUri().isEmpty()) {
          uri_ = other.uri_;
          onChanged();
        }
        if (!other.getSelection().isEmpty()) {
          selection_ = other.selection_;
          onChanged();
        }
        if (!other.selectionArgs_.isEmpty()) {
          if (selectionArgs_.isEmpty()) {
            selectionArgs_ = other.selectionArgs_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureSelectionArgsIsMutable();
            selectionArgs_.addAll(other.selectionArgs_);
          }
          onChanged();
        }
        internalGetMutableValues().mergeFrom(
            other.internalGetValues());
        if (!other.projection_.isEmpty()) {
          if (projection_.isEmpty()) {
            projection_ = other.projection_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureProjectionIsMutable();
            projection_.addAll(other.projection_);
          }
          onChanged();
        }
        if (!other.getSortOrder().isEmpty()) {
          sortOrder_ = other.sortOrder_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uuid_ = "";
      /**
       * <code>string uuid = 1;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       */
      public Builder clearUuid() {
        
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uuid_ = value;
        onChanged();
        return this;
      }

      private int method_ = 0;
      /**
       * <code>.Request.Method method = 2;</code>
       */
      public int getMethodValue() {
        return method_;
      }
      /**
       * <code>.Request.Method method = 2;</code>
       */
      public Builder setMethodValue(int value) {
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Request.Method method = 2;</code>
       */
      public com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.Method getMethod() {
        com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.Method result = com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.Method.valueOf(method_);
        return result == null ? com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.Method.UNRECOGNIZED : result;
      }
      /**
       * <code>.Request.Method method = 2;</code>
       */
      public Builder setMethod(com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request.Method value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        method_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Request.Method method = 2;</code>
       */
      public Builder clearMethod() {
        
        method_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object uri_ = "";
      /**
       * <pre>
       *method params
       * </pre>
       *
       * <code>string uri = 3;</code>
       */
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *method params
       * </pre>
       *
       * <code>string uri = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *method params
       * </pre>
       *
       * <code>string uri = 3;</code>
       */
      public Builder setUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uri_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *method params
       * </pre>
       *
       * <code>string uri = 3;</code>
       */
      public Builder clearUri() {
        
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *method params
       * </pre>
       *
       * <code>string uri = 3;</code>
       */
      public Builder setUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uri_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object selection_ = "";
      /**
       * <code>string selection = 4;</code>
       */
      public java.lang.String getSelection() {
        java.lang.Object ref = selection_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          selection_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string selection = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSelectionBytes() {
        java.lang.Object ref = selection_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          selection_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string selection = 4;</code>
       */
      public Builder setSelection(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        selection_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string selection = 4;</code>
       */
      public Builder clearSelection() {
        
        selection_ = getDefaultInstance().getSelection();
        onChanged();
        return this;
      }
      /**
       * <code>string selection = 4;</code>
       */
      public Builder setSelectionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        selection_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList selectionArgs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSelectionArgsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          selectionArgs_ = new com.google.protobuf.LazyStringArrayList(selectionArgs_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string selectionArgs = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSelectionArgsList() {
        return selectionArgs_.getUnmodifiableView();
      }
      /**
       * <code>repeated string selectionArgs = 5;</code>
       */
      public int getSelectionArgsCount() {
        return selectionArgs_.size();
      }
      /**
       * <code>repeated string selectionArgs = 5;</code>
       */
      public java.lang.String getSelectionArgs(int index) {
        return selectionArgs_.get(index);
      }
      /**
       * <code>repeated string selectionArgs = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSelectionArgsBytes(int index) {
        return selectionArgs_.getByteString(index);
      }
      /**
       * <code>repeated string selectionArgs = 5;</code>
       */
      public Builder setSelectionArgs(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSelectionArgsIsMutable();
        selectionArgs_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string selectionArgs = 5;</code>
       */
      public Builder addSelectionArgs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSelectionArgsIsMutable();
        selectionArgs_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string selectionArgs = 5;</code>
       */
      public Builder addAllSelectionArgs(
          java.lang.Iterable<java.lang.String> values) {
        ensureSelectionArgsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, selectionArgs_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string selectionArgs = 5;</code>
       */
      public Builder clearSelectionArgs() {
        selectionArgs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string selectionArgs = 5;</code>
       */
      public Builder addSelectionArgsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSelectionArgsIsMutable();
        selectionArgs_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> values_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetValues() {
        if (values_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        return values_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableValues() {
        onChanged();;
        if (values_ == null) {
          values_ = com.google.protobuf.MapField.newMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        if (!values_.isMutable()) {
          values_ = values_.copy();
        }
        return values_;
      }

      public int getValuesCount() {
        return internalGetValues().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; values = 6;</code>
       */

      public boolean containsValues(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetValues().getMap().containsKey(key);
      }
      /**
       * Use {@link #getValuesMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getValues() {
        return getValuesMap();
      }
      /**
       * <code>map&lt;string, string&gt; values = 6;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getValuesMap() {
        return internalGetValues().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; values = 6;</code>
       */

      public java.lang.String getValuesOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetValues().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; values = 6;</code>
       */

      public java.lang.String getValuesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetValues().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearValues() {
        internalGetMutableValues().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; values = 6;</code>
       */

      public Builder removeValues(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableValues().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableValues() {
        return internalGetMutableValues().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; values = 6;</code>
       */
      public Builder putValues(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableValues().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; values = 6;</code>
       */

      public Builder putAllValues(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableValues().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.LazyStringList projection_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureProjectionIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          projection_ = new com.google.protobuf.LazyStringArrayList(projection_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated string projection = 7;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getProjectionList() {
        return projection_.getUnmodifiableView();
      }
      /**
       * <code>repeated string projection = 7;</code>
       */
      public int getProjectionCount() {
        return projection_.size();
      }
      /**
       * <code>repeated string projection = 7;</code>
       */
      public java.lang.String getProjection(int index) {
        return projection_.get(index);
      }
      /**
       * <code>repeated string projection = 7;</code>
       */
      public com.google.protobuf.ByteString
          getProjectionBytes(int index) {
        return projection_.getByteString(index);
      }
      /**
       * <code>repeated string projection = 7;</code>
       */
      public Builder setProjection(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProjectionIsMutable();
        projection_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string projection = 7;</code>
       */
      public Builder addProjection(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProjectionIsMutable();
        projection_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string projection = 7;</code>
       */
      public Builder addAllProjection(
          java.lang.Iterable<java.lang.String> values) {
        ensureProjectionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, projection_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string projection = 7;</code>
       */
      public Builder clearProjection() {
        projection_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string projection = 7;</code>
       */
      public Builder addProjectionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureProjectionIsMutable();
        projection_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object sortOrder_ = "";
      /**
       * <code>string sortOrder = 8;</code>
       */
      public java.lang.String getSortOrder() {
        java.lang.Object ref = sortOrder_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sortOrder_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sortOrder = 8;</code>
       */
      public com.google.protobuf.ByteString
          getSortOrderBytes() {
        java.lang.Object ref = sortOrder_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sortOrder_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sortOrder = 8;</code>
       */
      public Builder setSortOrder(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sortOrder_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sortOrder = 8;</code>
       */
      public Builder clearSortOrder() {
        
        sortOrder_ = getDefaultInstance().getSortOrder();
        onChanged();
        return this;
      }
      /**
       * <code>string sortOrder = 8;</code>
       */
      public Builder setSortOrderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sortOrder_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Request)
    }

    // @@protoc_insertion_point(class_scope:Request)
    private static final com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request();
    }

    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uuid = 1;</code>
     */
    java.lang.String getUuid();
    /**
     * <code>string uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>.Response.Status status = 2;</code>
     */
    int getStatusValue();
    /**
     * <code>.Response.Status status = 2;</code>
     */
    com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.Status getStatus();

    /**
     * <pre>
     *result
     * </pre>
     *
     * <code>int32 intResult = 3;</code>
     */
    int getIntResult();

    /**
     * <pre>
     *Cursor resturns uuid
     * </pre>
     *
     * <code>string stringResult = 4;</code>
     */
    java.lang.String getStringResult();
    /**
     * <pre>
     *Cursor resturns uuid
     * </pre>
     *
     * <code>string stringResult = 4;</code>
     */
    com.google.protobuf.ByteString
        getStringResultBytes();
  }
  /**
   * Protobuf type {@code Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      uuid_ = "";
      status_ = 0;
      intResult_ = 0;
      stringResult_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uuid_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 24: {

              intResult_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              stringResult_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.internal_static_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.class, com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.Builder.class);
    }

    /**
     * Protobuf enum {@code Response.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Ok = 0;</code>
       */
      Ok(0),
      /**
       * <code>UriNotFound = 1;</code>
       */
      UriNotFound(1),
      /**
       * <code>MethodNotFound = 2;</code>
       */
      MethodNotFound(2),
      /**
       * <code>PermissionNotAllowed = 3;</code>
       */
      PermissionNotAllowed(3),
      /**
       * <code>UnknownError = 4;</code>
       */
      UnknownError(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>Ok = 0;</code>
       */
      public static final int Ok_VALUE = 0;
      /**
       * <code>UriNotFound = 1;</code>
       */
      public static final int UriNotFound_VALUE = 1;
      /**
       * <code>MethodNotFound = 2;</code>
       */
      public static final int MethodNotFound_VALUE = 2;
      /**
       * <code>PermissionNotAllowed = 3;</code>
       */
      public static final int PermissionNotAllowed_VALUE = 3;
      /**
       * <code>UnknownError = 4;</code>
       */
      public static final int UnknownError_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      public static Status forNumber(int value) {
        switch (value) {
          case 0: return Ok;
          case 1: return UriNotFound;
          case 2: return MethodNotFound;
          case 3: return PermissionNotAllowed;
          case 4: return UnknownError;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Response.Status)
    }

    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uuid_;
    /**
     * <code>string uuid = 1;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <code>string uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <code>.Response.Status status = 2;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.Response.Status status = 2;</code>
     */
    public com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.Status getStatus() {
      com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.Status result = com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.Status.valueOf(status_);
      return result == null ? com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.Status.UNRECOGNIZED : result;
    }

    public static final int INTRESULT_FIELD_NUMBER = 3;
    private int intResult_;
    /**
     * <pre>
     *result
     * </pre>
     *
     * <code>int32 intResult = 3;</code>
     */
    public int getIntResult() {
      return intResult_;
    }

    public static final int STRINGRESULT_FIELD_NUMBER = 4;
    private volatile java.lang.Object stringResult_;
    /**
     * <pre>
     *Cursor resturns uuid
     * </pre>
     *
     * <code>string stringResult = 4;</code>
     */
    public java.lang.String getStringResult() {
      java.lang.Object ref = stringResult_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stringResult_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *Cursor resturns uuid
     * </pre>
     *
     * <code>string stringResult = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStringResultBytes() {
      java.lang.Object ref = stringResult_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      if (status_ != com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.Status.Ok.getNumber()) {
        output.writeEnum(2, status_);
      }
      if (intResult_ != 0) {
        output.writeInt32(3, intResult_);
      }
      if (!getStringResultBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, stringResult_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      if (status_ != com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.Status.Ok.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_);
      }
      if (intResult_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, intResult_);
      }
      if (!getStringResultBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, stringResult_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response)) {
        return super.equals(obj);
      }
      com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response other = (com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response) obj;

      boolean result = true;
      result = result && getUuid()
          .equals(other.getUuid());
      result = result && status_ == other.status_;
      result = result && (getIntResult()
          == other.getIntResult());
      result = result && getStringResult()
          .equals(other.getStringResult());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + INTRESULT_FIELD_NUMBER;
      hash = (53 * hash) + getIntResult();
      hash = (37 * hash) + STRINGRESULT_FIELD_NUMBER;
      hash = (53 * hash) + getStringResult().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.internal_static_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.class, com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.Builder.class);
      }

      // Construct using com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uuid_ = "";

        status_ = 0;

        intResult_ = 0;

        stringResult_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.internal_static_Response_descriptor;
      }

      public com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response getDefaultInstanceForType() {
        return com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.getDefaultInstance();
      }

      public com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response build() {
        com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response buildPartial() {
        com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response result = new com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response(this);
        result.uuid_ = uuid_;
        result.status_ = status_;
        result.intResult_ = intResult_;
        result.stringResult_ = stringResult_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response) {
          return mergeFrom((com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response other) {
        if (other == com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.getDefaultInstance()) return this;
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (other.getIntResult() != 0) {
          setIntResult(other.getIntResult());
        }
        if (!other.getStringResult().isEmpty()) {
          stringResult_ = other.stringResult_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <code>string uuid = 1;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       */
      public Builder clearUuid() {
        
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uuid_ = value;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.Response.Status status = 2;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.Response.Status status = 2;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Response.Status status = 2;</code>
       */
      public com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.Status getStatus() {
        com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.Status result = com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.Status.valueOf(status_);
        return result == null ? com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.Response.Status status = 2;</code>
       */
      public Builder setStatus(com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Response.Status status = 2;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private int intResult_ ;
      /**
       * <pre>
       *result
       * </pre>
       *
       * <code>int32 intResult = 3;</code>
       */
      public int getIntResult() {
        return intResult_;
      }
      /**
       * <pre>
       *result
       * </pre>
       *
       * <code>int32 intResult = 3;</code>
       */
      public Builder setIntResult(int value) {
        
        intResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *result
       * </pre>
       *
       * <code>int32 intResult = 3;</code>
       */
      public Builder clearIntResult() {
        
        intResult_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object stringResult_ = "";
      /**
       * <pre>
       *Cursor resturns uuid
       * </pre>
       *
       * <code>string stringResult = 4;</code>
       */
      public java.lang.String getStringResult() {
        java.lang.Object ref = stringResult_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stringResult_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *Cursor resturns uuid
       * </pre>
       *
       * <code>string stringResult = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStringResultBytes() {
        java.lang.Object ref = stringResult_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringResult_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *Cursor resturns uuid
       * </pre>
       *
       * <code>string stringResult = 4;</code>
       */
      public Builder setStringResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stringResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Cursor resturns uuid
       * </pre>
       *
       * <code>string stringResult = 4;</code>
       */
      public Builder clearStringResult() {
        
        stringResult_ = getDefaultInstance().getStringResult();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Cursor resturns uuid
       * </pre>
       *
       * <code>string stringResult = 4;</code>
       */
      public Builder setStringResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stringResult_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response();
    }

    public static com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public com.github.hsingpeng.extendbinder.proto.ContentProviderMsg.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_ValuesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_ValuesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026content_provider.proto\"\261\002\n\007Request\022\014\n\004" +
      "uuid\030\001 \001(\t\022\037\n\006method\030\002 \001(\0162\017.Request.Met" +
      "hod\022\013\n\003uri\030\003 \001(\t\022\021\n\tselection\030\004 \001(\t\022\025\n\rs" +
      "electionArgs\030\005 \003(\t\022$\n\006values\030\006 \003(\0132\024.Req" +
      "uest.ValuesEntry\022\022\n\nprojection\030\007 \003(\t\022\021\n\t" +
      "sortOrder\030\010 \001(\t\032-\n\013ValuesEntry\022\013\n\003key\030\001 " +
      "\001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"D\n\006Method\022\n\n\006dele" +
      "te\020\000\022\013\n\007getType\020\001\022\n\n\006insert\020\002\022\t\n\005query\020\003" +
      "\022\n\n\006update\020\004\"\306\001\n\010Response\022\014\n\004uuid\030\001 \001(\t\022" +
      " \n\006status\030\002 \001(\0162\020.Response.Status\022\021\n\tint" +
      "Result\030\003 \001(\005\022\024\n\014stringResult\030\004 \001(\t\"a\n\006St" +
      "atus\022\006\n\002Ok\020\000\022\017\n\013UriNotFound\020\001\022\022\n\016MethodN" +
      "otFound\020\002\022\030\n\024PermissionNotAllowed\020\003\022\020\n\014U" +
      "nknownError\020\004B=\n\'com.github.hsingpeng.ex" +
      "tendbinder.protoB\022ContentProviderMsgb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "Uuid", "Method", "Uri", "Selection", "SelectionArgs", "Values", "Projection", "SortOrder", });
    internal_static_Request_ValuesEntry_descriptor =
      internal_static_Request_descriptor.getNestedTypes().get(0);
    internal_static_Request_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_ValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Uuid", "Status", "IntResult", "StringResult", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
