// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: intent.proto

package com.github.hsingpeng.extendbinder.proto;

public final class IntentMsg {
  private IntentMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Request.Method method = 8;</code>
     */
    int getMethodValue();
    /**
     * <code>.Request.Method method = 8;</code>
     */
    Request.Method getMethod();

    /**
     * <code>string action = 1;</code>
     */
    String getAction();
    /**
     * <code>string action = 1;</code>
     */
    com.google.protobuf.ByteString
        getActionBytes();

    /**
     * <code>string className = 2;</code>
     */
    String getClassName();
    /**
     * <code>string className = 2;</code>
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    /**
     * <code>string packageName = 3;</code>
     */
    String getPackageName();
    /**
     * <code>string packageName = 3;</code>
     */
    com.google.protobuf.ByteString
        getPackageNameBytes();

    /**
     * <code>string type = 4;</code>
     */
    String getType();
    /**
     * <code>string type = 4;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>repeated string categories = 5;</code>
     */
    java.util.List<String>
        getCategoriesList();
    /**
     * <code>repeated string categories = 5;</code>
     */
    int getCategoriesCount();
    /**
     * <code>repeated string categories = 5;</code>
     */
    String getCategories(int index);
    /**
     * <code>repeated string categories = 5;</code>
     */
    com.google.protobuf.ByteString
        getCategoriesBytes(int index);

    /**
     * <code>string uri = 6;</code>
     */
    String getUri();
    /**
     * <code>string uri = 6;</code>
     */
    com.google.protobuf.ByteString
        getUriBytes();

    /**
     * <code>map&lt;string, string&gt; extras = 7;</code>
     */
    int getExtrasCount();
    /**
     * <code>map&lt;string, string&gt; extras = 7;</code>
     */
    boolean containsExtras(
            String key);
    /**
     * Use {@link #getExtrasMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getExtras();
    /**
     * <code>map&lt;string, string&gt; extras = 7;</code>
     */
    java.util.Map<String, String>
    getExtrasMap();
    /**
     * <code>map&lt;string, string&gt; extras = 7;</code>
     */

    String getExtrasOrDefault(
            String key,
            String defaultValue);
    /**
     * <code>map&lt;string, string&gt; extras = 7;</code>
     */

    String getExtrasOrThrow(
            String key);
  }
  /**
   * Protobuf type {@code Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      method_ = 0;
      action_ = "";
      className_ = "";
      packageName_ = "";
      type_ = "";
      categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      uri_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              action_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              className_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              packageName_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                categories_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              categories_.add(s);
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              uri_ = s;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                extras_ = com.google.protobuf.MapField.newMapField(
                    ExtrasDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000080;
              }
              com.google.protobuf.MapEntry<String, String>
              extras__ = input.readMessage(
                  ExtrasDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              extras_.getMutableMap().put(
                  extras__.getKey(), extras__.getValue());
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              method_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          categories_ = categories_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IntentMsg.internal_static_Request_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetExtras();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IntentMsg.internal_static_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Request.class, Builder.class);
    }

    /**
     * Protobuf enum {@code Request.Method}
     */
    public enum Method
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>startActivity = 0;</code>
       */
      startActivity(0),
      /**
       * <code>startService = 1;</code>
       */
      startService(1),
      /**
       * <code>sendBroadcast = 2;</code>
       */
      sendBroadcast(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>startActivity = 0;</code>
       */
      public static final int startActivity_VALUE = 0;
      /**
       * <code>startService = 1;</code>
       */
      public static final int startService_VALUE = 1;
      /**
       * <code>sendBroadcast = 2;</code>
       */
      public static final int sendBroadcast_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Method valueOf(int value) {
        return forNumber(value);
      }

      public static Method forNumber(int value) {
        switch (value) {
          case 0: return startActivity;
          case 1: return startService;
          case 2: return sendBroadcast;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Method>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Method> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Method>() {
              public Method findValueByNumber(int number) {
                return Method.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Request.getDescriptor().getEnumTypes().get(0);
      }

      private static final Method[] VALUES = values();

      public static Method valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Method(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Request.Method)
    }

    private int bitField0_;
    public static final int METHOD_FIELD_NUMBER = 8;
    private int method_;
    /**
     * <code>.Request.Method method = 8;</code>
     */
    public int getMethodValue() {
      return method_;
    }
    /**
     * <code>.Request.Method method = 8;</code>
     */
    public Method getMethod() {
      Method result = Method.valueOf(method_);
      return result == null ? Method.UNRECOGNIZED : result;
    }

    public static final int ACTION_FIELD_NUMBER = 1;
    private volatile Object action_;
    /**
     * <code>string action = 1;</code>
     */
    public String getAction() {
      Object ref = action_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        action_ = s;
        return s;
      }
    }
    /**
     * <code>string action = 1;</code>
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLASSNAME_FIELD_NUMBER = 2;
    private volatile Object className_;
    /**
     * <code>string className = 2;</code>
     */
    public String getClassName() {
      Object ref = className_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        className_ = s;
        return s;
      }
    }
    /**
     * <code>string className = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      Object ref = className_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PACKAGENAME_FIELD_NUMBER = 3;
    private volatile Object packageName_;
    /**
     * <code>string packageName = 3;</code>
     */
    public String getPackageName() {
      Object ref = packageName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        packageName_ = s;
        return s;
      }
    }
    /**
     * <code>string packageName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      Object ref = packageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        packageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private volatile Object type_;
    /**
     * <code>string type = 4;</code>
     */
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CATEGORIES_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList categories_;
    /**
     * <code>repeated string categories = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getCategoriesList() {
      return categories_;
    }
    /**
     * <code>repeated string categories = 5;</code>
     */
    public int getCategoriesCount() {
      return categories_.size();
    }
    /**
     * <code>repeated string categories = 5;</code>
     */
    public String getCategories(int index) {
      return categories_.get(index);
    }
    /**
     * <code>repeated string categories = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCategoriesBytes(int index) {
      return categories_.getByteString(index);
    }

    public static final int URI_FIELD_NUMBER = 6;
    private volatile Object uri_;
    /**
     * <code>string uri = 6;</code>
     */
    public String getUri() {
      Object ref = uri_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        uri_ = s;
        return s;
      }
    }
    /**
     * <code>string uri = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUriBytes() {
      Object ref = uri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTRAS_FIELD_NUMBER = 7;
    private static final class ExtrasDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, String>newDefaultInstance(
                  IntentMsg.internal_static_Request_ExtrasEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        String, String> extras_;
    private com.google.protobuf.MapField<String, String>
    internalGetExtras() {
      if (extras_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ExtrasDefaultEntryHolder.defaultEntry);
      }
      return extras_;
    }

    public int getExtrasCount() {
      return internalGetExtras().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; extras = 7;</code>
     */

    public boolean containsExtras(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetExtras().getMap().containsKey(key);
    }
    /**
     * Use {@link #getExtrasMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, String> getExtras() {
      return getExtrasMap();
    }
    /**
     * <code>map&lt;string, string&gt; extras = 7;</code>
     */

    public java.util.Map<String, String> getExtrasMap() {
      return internalGetExtras().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; extras = 7;</code>
     */

    public String getExtrasOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetExtras().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; extras = 7;</code>
     */

    public String getExtrasOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetExtras().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getActionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, action_);
      }
      if (!getClassNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, className_);
      }
      if (!getPackageNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, packageName_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, type_);
      }
      for (int i = 0; i < categories_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, categories_.getRaw(i));
      }
      if (!getUriBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, uri_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetExtras(),
          ExtrasDefaultEntryHolder.defaultEntry,
          7);
      if (method_ != Method.startActivity.getNumber()) {
        output.writeEnum(8, method_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getActionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, action_);
      }
      if (!getClassNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, className_);
      }
      if (!getPackageNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, packageName_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, type_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < categories_.size(); i++) {
          dataSize += computeStringSizeNoTag(categories_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getCategoriesList().size();
      }
      if (!getUriBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, uri_);
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetExtras().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        extras__ = ExtrasDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(7, extras__);
      }
      if (method_ != Method.startActivity.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, method_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Request)) {
        return super.equals(obj);
      }
      Request other = (Request) obj;

      boolean result = true;
      result = result && method_ == other.method_;
      result = result && getAction()
          .equals(other.getAction());
      result = result && getClassName()
          .equals(other.getClassName());
      result = result && getPackageName()
          .equals(other.getPackageName());
      result = result && getType()
          .equals(other.getType());
      result = result && getCategoriesList()
          .equals(other.getCategoriesList());
      result = result && getUri()
          .equals(other.getUri());
      result = result && internalGetExtras().equals(
          other.internalGetExtras());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + method_;
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
      hash = (37 * hash) + CLASSNAME_FIELD_NUMBER;
      hash = (53 * hash) + getClassName().hashCode();
      hash = (37 * hash) + PACKAGENAME_FIELD_NUMBER;
      hash = (53 * hash) + getPackageName().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      if (getCategoriesCount() > 0) {
        hash = (37 * hash) + CATEGORIES_FIELD_NUMBER;
        hash = (53 * hash) + getCategoriesList().hashCode();
      }
      hash = (37 * hash) + URI_FIELD_NUMBER;
      hash = (53 * hash) + getUri().hashCode();
      if (!internalGetExtras().getMap().isEmpty()) {
        hash = (37 * hash) + EXTRAS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetExtras().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Request)
        RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IntentMsg.internal_static_Request_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetExtras();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetMutableExtras();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IntentMsg.internal_static_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Request.class, Builder.class);
      }

      // Construct using com.github.hsingpeng.extendbinder.proto.IntentMsg.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        method_ = 0;

        action_ = "";

        className_ = "";

        packageName_ = "";

        type_ = "";

        categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        uri_ = "";

        internalGetMutableExtras().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IntentMsg.internal_static_Request_descriptor;
      }

      public Request getDefaultInstanceForType() {
        return Request.getDefaultInstance();
      }

      public Request build() {
        Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Request buildPartial() {
        Request result = new Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.method_ = method_;
        result.action_ = action_;
        result.className_ = className_;
        result.packageName_ = packageName_;
        result.type_ = type_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          categories_ = categories_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.categories_ = categories_;
        result.uri_ = uri_;
        result.extras_ = internalGetExtras();
        result.extras_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Request) {
          return mergeFrom((Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Request other) {
        if (other == Request.getDefaultInstance()) return this;
        if (other.method_ != 0) {
          setMethodValue(other.getMethodValue());
        }
        if (!other.getAction().isEmpty()) {
          action_ = other.action_;
          onChanged();
        }
        if (!other.getClassName().isEmpty()) {
          className_ = other.className_;
          onChanged();
        }
        if (!other.getPackageName().isEmpty()) {
          packageName_ = other.packageName_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.categories_.isEmpty()) {
          if (categories_.isEmpty()) {
            categories_ = other.categories_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureCategoriesIsMutable();
            categories_.addAll(other.categories_);
          }
          onChanged();
        }
        if (!other.getUri().isEmpty()) {
          uri_ = other.uri_;
          onChanged();
        }
        internalGetMutableExtras().mergeFrom(
            other.internalGetExtras());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int method_ = 0;
      /**
       * <code>.Request.Method method = 8;</code>
       */
      public int getMethodValue() {
        return method_;
      }
      /**
       * <code>.Request.Method method = 8;</code>
       */
      public Builder setMethodValue(int value) {
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Request.Method method = 8;</code>
       */
      public Method getMethod() {
        Method result = Method.valueOf(method_);
        return result == null ? Method.UNRECOGNIZED : result;
      }
      /**
       * <code>.Request.Method method = 8;</code>
       */
      public Builder setMethod(Method value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        method_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Request.Method method = 8;</code>
       */
      public Builder clearMethod() {
        
        method_ = 0;
        onChanged();
        return this;
      }

      private Object action_ = "";
      /**
       * <code>string action = 1;</code>
       */
      public String getAction() {
        Object ref = action_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string action = 1;</code>
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string action = 1;</code>
       */
      public Builder setAction(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string action = 1;</code>
       */
      public Builder clearAction() {
        
        action_ = getDefaultInstance().getAction();
        onChanged();
        return this;
      }
      /**
       * <code>string action = 1;</code>
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        action_ = value;
        onChanged();
        return this;
      }

      private Object className_ = "";
      /**
       * <code>string className = 2;</code>
       */
      public String getClassName() {
        Object ref = className_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          className_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string className = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        Object ref = className_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          className_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string className = 2;</code>
       */
      public Builder setClassName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        className_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string className = 2;</code>
       */
      public Builder clearClassName() {
        
        className_ = getDefaultInstance().getClassName();
        onChanged();
        return this;
      }
      /**
       * <code>string className = 2;</code>
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        className_ = value;
        onChanged();
        return this;
      }

      private Object packageName_ = "";
      /**
       * <code>string packageName = 3;</code>
       */
      public String getPackageName() {
        Object ref = packageName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          packageName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string packageName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPackageNameBytes() {
        Object ref = packageName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          packageName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string packageName = 3;</code>
       */
      public Builder setPackageName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        packageName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string packageName = 3;</code>
       */
      public Builder clearPackageName() {
        
        packageName_ = getDefaultInstance().getPackageName();
        onChanged();
        return this;
      }
      /**
       * <code>string packageName = 3;</code>
       */
      public Builder setPackageNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        packageName_ = value;
        onChanged();
        return this;
      }

      private Object type_ = "";
      /**
       * <code>string type = 4;</code>
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string type = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 4;</code>
       */
      public Builder setType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 4;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCategoriesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          categories_ = new com.google.protobuf.LazyStringArrayList(categories_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string categories = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getCategoriesList() {
        return categories_.getUnmodifiableView();
      }
      /**
       * <code>repeated string categories = 5;</code>
       */
      public int getCategoriesCount() {
        return categories_.size();
      }
      /**
       * <code>repeated string categories = 5;</code>
       */
      public String getCategories(int index) {
        return categories_.get(index);
      }
      /**
       * <code>repeated string categories = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCategoriesBytes(int index) {
        return categories_.getByteString(index);
      }
      /**
       * <code>repeated string categories = 5;</code>
       */
      public Builder setCategories(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCategoriesIsMutable();
        categories_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string categories = 5;</code>
       */
      public Builder addCategories(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCategoriesIsMutable();
        categories_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string categories = 5;</code>
       */
      public Builder addAllCategories(
          Iterable<String> values) {
        ensureCategoriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, categories_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string categories = 5;</code>
       */
      public Builder clearCategories() {
        categories_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string categories = 5;</code>
       */
      public Builder addCategoriesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureCategoriesIsMutable();
        categories_.add(value);
        onChanged();
        return this;
      }

      private Object uri_ = "";
      /**
       * <code>string uri = 6;</code>
       */
      public String getUri() {
        Object ref = uri_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string uri = 6;</code>
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        Object ref = uri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uri = 6;</code>
       */
      public Builder setUri(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uri = 6;</code>
       */
      public Builder clearUri() {
        
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      /**
       * <code>string uri = 6;</code>
       */
      public Builder setUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uri_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, String> extras_;
      private com.google.protobuf.MapField<String, String>
      internalGetExtras() {
        if (extras_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ExtrasDefaultEntryHolder.defaultEntry);
        }
        return extras_;
      }
      private com.google.protobuf.MapField<String, String>
      internalGetMutableExtras() {
        onChanged();;
        if (extras_ == null) {
          extras_ = com.google.protobuf.MapField.newMapField(
              ExtrasDefaultEntryHolder.defaultEntry);
        }
        if (!extras_.isMutable()) {
          extras_ = extras_.copy();
        }
        return extras_;
      }

      public int getExtrasCount() {
        return internalGetExtras().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; extras = 7;</code>
       */

      public boolean containsExtras(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetExtras().getMap().containsKey(key);
      }
      /**
       * Use {@link #getExtrasMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, String> getExtras() {
        return getExtrasMap();
      }
      /**
       * <code>map&lt;string, string&gt; extras = 7;</code>
       */

      public java.util.Map<String, String> getExtrasMap() {
        return internalGetExtras().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; extras = 7;</code>
       */

      public String getExtrasOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetExtras().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; extras = 7;</code>
       */

      public String getExtrasOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetExtras().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearExtras() {
        internalGetMutableExtras().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; extras = 7;</code>
       */

      public Builder removeExtras(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableExtras().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, String>
      getMutableExtras() {
        return internalGetMutableExtras().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; extras = 7;</code>
       */
      public Builder putExtras(
          String key,
          String value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableExtras().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; extras = 7;</code>
       */

      public Builder putAllExtras(
          java.util.Map<String, String> values) {
        internalGetMutableExtras().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Request)
    }

    // @@protoc_insertion_point(class_scope:Request)
    private static final Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Request();
    }

    public static Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_ExtrasEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_ExtrasEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014intent.proto\"\250\002\n\007Request\022\037\n\006method\030\010 \001" +
      "(\0162\017.Request.Method\022\016\n\006action\030\001 \001(\t\022\021\n\tc" +
      "lassName\030\002 \001(\t\022\023\n\013packageName\030\003 \001(\t\022\014\n\004t" +
      "ype\030\004 \001(\t\022\022\n\ncategories\030\005 \003(\t\022\013\n\003uri\030\006 \001" +
      "(\t\022$\n\006extras\030\007 \003(\0132\024.Request.ExtrasEntry" +
      "\032-\n\013ExtrasEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t:\0028\001\"@\n\006Method\022\021\n\rstartActivity\020\000\022\020\n\014" +
      "startService\020\001\022\021\n\rsendBroadcast\020\002B4\n\'com" +
      ".github.hsingpeng.extendbinder.protoB\tIn" +
      "tentMsgb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new String[] { "Method", "Action", "ClassName", "PackageName", "Type", "Categories", "Uri", "Extras", });
    internal_static_Request_ExtrasEntry_descriptor =
      internal_static_Request_descriptor.getNestedTypes().get(0);
    internal_static_Request_ExtrasEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_ExtrasEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
